### ISSUE TITLE
Processing 3 Compatibility

### ISSUE THREAD

**Issue by cbutelli** [extrapixel/gif-animation#15]
I'm getting the "NoSuchMethodError: You may be using a library that's incompatible with this version of Processing" error when running a sketch with code relating to the library :(

**Comment by embedded-creations** [comment]
Use this port: https://github.com/01010101/GifAnimation

**Comment by embedded-creations** [comment]
Or use the 3.0 branch from this repo: https://github.com/extrapixel/gif-animation/tree/3.0

**Comment by villares** [comment]
Hi, what is missing to put this 3.0 branch back into the IDE's Libraries manager?

**Comment by extrapixel** [comment]
Anyone of you guys interested to take over this project?

**Comment by extrapixel** [comment]
see 3.0 branch: https://github.com/extrapixel/gif-animation/tree/3.0
