### ISSUE TITLE
multiple gifs

### ISSUE THREAD

**Issue by tarbear123** [extrapixel/gif-animation#28]
would I put a Delay between each gif if i wanted to have a delay before the next gif and what do the numbers mean in the brackets?

```
void draw() {
image(myAnimation, 10,10);

image(myAnimation1, 10,10);

image(myAnimation2, 10,10);

image(myAnimation3, 10,10);

image(myAnimation4, 10,10);

image(myAnimation5, 10,10);

image(myAnimation6, 10,10);

image(myAnimation7, 10,10);

image(myAnimation8, 10,10);

image(myAnimation9, 10,10);

image(myAnimation10, 10,10);

image(myAnimation11, 10,10);
}
```

**Comment by hamoid** [comment]
What this program would do is draw a bunch of images on top of each other, and probably only the last one would be visible (covering all the previous ones). I think this is a question for the forum: https://discourse.processing.org/ as it is about basic Processing usage.
