### ISSUE TITLE
Updating to v2.3.1 results in version v2.3 being installed instead

### ISSUE THREAD

**Issue by JobLeonard** [extrapixel/gif-animation#3]
So the update manager keeps telling me there's a new version of this library. So I try to update, and then end up with the old version.

Uninstalling and then re-installing does not seem to help.

Not sure if the problem is with this library, or with the PDE itself, but I figured I'd open an issue here first.

**Comment by extrapixel** [comment]
Sorry about this. Just pulled a few chanes from all the forks. There will be an "official" update to 2.4 once the new code is tested. Feel free to download the newest from this repo and test :)
